### ISSUE TITLE
Does _vestingSchedule never vest before 100%?

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/vw-cli#3]
Function in question: https://github.com/oceanprotocol/vw-cli/blob/aac5bddb1bc070f1cadbb0bff58c501f27a75f8a/contracts/VestingWallet.sol#L132

- `block.timestamp` is in seconds: https://docs.soliditylang.org/en/latest/units-and-global-variables.html?highlight=block#block-and-transaction-properties
- duration is in seconds (at least indicated by variable name): https://github.com/oceanprotocol/vw-cli/blob/aac5bddb1bc070f1cadbb0bff58c501f27a75f8a/contracts/VestingWallet.sol#L41
- Solidity integer division never yields a floating-point number but instead rounds down to the closest integer: `1/2 = 0, 100/1000 = 0, etc.`

Hence for `_vestingSchedule`, if let's say we have today's unix epoch as `block.timestamp` 1649328191 and yesterday's timestamp as a start 1649328191-86400=1649241791, if we have a duration of two days of vesting: 86400*2=172800, today I should be able to claim 50% of my token.

But, since Solidity's integer division doesn't yield decimals, we wouldn't get any tokens.

From my understanding, this is why others are scaling up the values in the vision to create "per-cent-ages": https://github.com/Rari-Capital/solmate/blob/4eaf6b68202e36f67cab379768ac6be304c8ebde/src/utils/FixedPointMathLib.sol#L7 I ran into this problem too: https://github.com/rugpullindex/libharberger/blob/ed0beed6616d5b08b4ff10e2521ce0744d6ddf06/src/Harberger.sol#L6

I've demonstrated what I mean in code here, albeit it being written in foundry and not brownie: https://github.com/TimDaub/vw-cli/blob/f5f53b0fce1fa486ebe5fd72847365a907ffa714/src/VestingWallet.t.sol#L23

**Comment by trentmc** [comment]
Correct, as it's currently set, it's just a cliff, not percentages. This was intentional, for our use case in Ocean.

As the README says:
> Potential future features:
> CLI currently supports fixed lock time ("cliff of x"); could pull up contract functionality for linear vesting

I've got a couple versions with percentage vesting, in TokenSPICE repo:
- [VestingWallet057.sol](https://github.com/tokenspice/tokenspice/blob/main/sol057/contracts/scheduler057/VestingWallet057.sol) - almost direct copy of OpenZeppelin code. Problem: ganache dies past year 2038 (Y2038 problem - integer overflow on unix time)
- [VestingWallet080.sol](https://github.com/tokenspice/tokenspice/blob/main/sol080/contracts/scheduler080/VestingWallet080.sol) - fixes Y2038 problem by switching time units from "unix time" to "# blocks"

So VestingWallet080.sol could be brought into this repo. But I'd have to update the CLI. Right now I'm focusing on other stuff. If you wanted to do it, go for it! :)

**Comment by TimDaub** [comment]
VW57 and VW80 have the same problem.
